// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThongKeCCCD.Data
{
    public partial class CoQuanBhxh
    {
        public string MaHuyen { get; set; }
        public string Ten { get; set; }
    }
}