// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ThongKeCCCD.Data
{
    public partial class NguoiThamGia
    {
        public int Id { get; set; }
        public string MaDvi { get; set; }
        public string MaHuyen { get; set; }
        public string SoBhxh { get; set; }
        public string SoKcb { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public string NgaySinh { get; set; }
        public string SoCmnd { get; set; }
        public string DangNhapVssid { get; set; }
        public string DaDangKyVssid { get; set; }
        public string TrangThaiXacThuc { get; set; }
        public string SoDdcnCccdBca { get; set; }
        public string ThongTinKhongChinhXac { get; set; }
    }
}